### ISSUE TITLE
[ERROR]: Business Area's not completed-present for E2E - Order to Cash 

### ISSUE THREAD

**Issue by ralph-work** [microsoft/dynamics365patternspractices#111]
### Contact Details

ralph###.work@###.com

### Describe the error you see in the documentation, or the correction you suggest

There are 3 business area's (and subsequent business proces, patterns) that are not present/completed and or vice versa

65.10.0xx.x00 - Manage store operations (Guidance hub NO - BPC YES)
65.x0.0xx.x00 - Manage pricing and contracts (Guidance hub YES, BPC NO)
65.x0.0xx.x00 - Trade across companies (Guidance hub YES, BPC NO)
65.x0.0xx.x00 - Process customer rebates (Guidance hub YES, BPC NO)

### Link to the article where the error is

https://learn.microsoft.com/en-us/dynamics365/guidance/business-processes/order-to-cash-overview  https://github.com/microsoft/dynamics365patternspractices/blob/main/templates/business-processes/Business%20Process%20Catalog%20October%202023.xlsx

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rachel-profitt** [comment]
Changes to the articles have been submitted and will be published in the next round of publishing. The articles will now reflect the updates that are in the catalog. Thanks for submitting your feedback.

**Comment by ralph-work** [comment]
thank you! your feedback is appreciated
