### ISSUE TITLE
[ERROR]: Business Area's not completed-present for E2E - Procure to Pay

### ISSUE THREAD

**Issue by ralph-work** [microsoft/dynamics365patternspractices#112]
### Contact Details

ralph###.work@###.com

### Describe the error you see in the documentation, or the correction you suggest

There are 5 business area's (and subsequent business proces, patterns) that are not present/completed

75.x0.0xx.x00 - Define policies and procedures for procurement (Guidance hub YES, BPC NO)
75.x0.0xx.x00 - Plan supply (Guidance hub YES, BPC NO)
75.x0.0xx.x00 - Manage vendor debits and chargebacks (Guidance hub YES, BPC NO)
75.x0.0xx.x00 - Create and proces promissory notes (Guidance hub YES, BPC NO)
75.x0.0xx.x00 - Analyse vendor preformance (Guidance hub YES, BPC NO)

### Link to the article where the error is

https://learn.microsoft.com/en-us/dynamics365/guidance/business-processes/procure-to-pay-overview  https://github.com/microsoft/dynamics365patternspractices/blob/main/templates/business-processes/Business%20Process%20Catalog%20October%202023.xlsx

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by edupont04** [comment]
Hello, thank you for your suggestion. The articles for the different business process areas are work in progress. New articles are added every other week, and the ones missing for procure-to-pay will probably come either later in December 2023 or in January 2024.

**Comment by AdiVijayashankar** [comment]
Thank you for the suggestion. The following changes will be made to the learn article. However, the business process cataloque is already reflecting the below changes. 

"Plan supply" business process will move to Forecast to plan end to end business process

"Define procurement and sourcing policies" will be converted to a L3 business process under the L2 business process area "Define procurement and sourcing strategies"

"Evaluate vendor performance" will be converted to a L3 business process under the L2 business process area "Manage vendor relationship"

"Process vendor debits" will be converted to a L3 business process under the L2 business process area "Process vendor invoices"

"Generate and process promissory notes" will be converted to a L3 business process under the L2 business process area "Issue and settle vendor payments"
