### ISSUE TITLE
[BUSINESS PROCESS]: Create vendors

### ISSUE THREAD

**Issue by rachel-profitt** [microsoft/dynamics365patternspractices#142]
### Contact details

raprofit@microsoft.com

### Organization type

Microsoft employee

### End-to-end business process

Procure to pay

### Which business process area is this article related to?

Manage vendor relationships

### Enter the name of the business process you are starting work on

Create vendors

### Enter any additional comments or information you want us to know.

Comments go here

### Specify the date you expect the article to be completed and ready for review.

3/1/2024

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdiVijayashankar** [comment]
Duplicate
