### ISSUE TITLE
[CATALOG]: Business Process Catalog DEC2023.xlsx duplicity

### ISSUE THREAD

**Issue by fandas-eu** [microsoft/dynamics365patternspractices#201]
### Contact details

frantisek.smid@aricoma.com

### Organization type

Partner / ISV / Independant consultant

### End-to-end business process

Acquire to dispose

### Which business process area is this article related to?

-

### Which business process is this article related to?

-

### Which pattern or practice is this request related to?

-

### Please describe the suggested change. If this is an update to an existing row in the catalog, please be sure to indicate in the comments.

Hello Rachel, I observed some duplicities in sequence code ID:
10.30.020
55.10.040
55.40.050
55.60.060.100
65.30.025
65.30.045
80.40.160
80.40.160.100
80.40.160.200
80.40.160.300
85.20.030
85.60.050
90.60.090
90.60.090.100

From my point of view it is about wrong numbering.

Regards, 
Frantisek

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rachel-profitt** [comment]
Thanks Frantisek, these numbers will be updated in the next release of the catalog which is expected to come out next week.
