### ISSUE TITLE
[AREA]: Define production strategies

### ISSUE THREAD

**Issue by rachel-profitt** [microsoft/dynamics365patternspractices#32]
### Contact details

maotte@microsoft.com

### Organization type

Microsoft employee

### End-to-end business process

Plan to produce

### Specify the business process area name for the article.

Define production strategies

### Enter any additional comments or information you want us to know about this business process area.

Draft in progress

### Specify the date you expect the article to be completed and ready for review.

7/31/2023

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by annekrupke** [comment]
This is now in technical review - I still do not have access to update issue statuses I think
